spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin
    url: jdbc:postgresql://localhost:5435/payment_service
    hikari:
      maximum-pool-size: 10 #max connect at the time
      minimum-idle: 2 #min connect at the time
      idle-timeout: 30000 #milisec
      connection-timeout: 30000 #milisec
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8096

