spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: user-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  servlet:
    context-path: /user
