
server:
  servlet:
    context-path: /identity

spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: identity-service

jwt:
  signerKey: "cS6BxiaKDa2unnbvzjzObquWcvFQjtXgnNByk3qRoQ+dtnTykVToROhj4y86bpK6"
  valid-duration: 360000 #sec
  refreshable-duration: 3600000 #sec

file:
  default-avatar-file-name: "4eb64364-7e5a-4eae-b2bd-a0aec8d3aff6.jpg"